version: '3.4'

services:
  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
          - "8081:80"
      networks:
          - frontend
      volumes:
          - ../www:/var/www/
          - ./nginx/conf:/etc/nginx/conf.d
          - ./nginx/logs:/var/log/nginx/
      depends_on:
          - app
  app:
      build: ./php
      container_name: app
      networks:
          - backend
          - frontend
      volumes:
          - ./www:/var/www/
      depends_on:
          - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_DATABASE=sistema
      - MYSQL_USER=sistema
      - MYSQL_PASSWORD=secret
    volumes:
        - ./mysql/data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    networks:
        - backend
networks:
    backend:
    frontend:
