version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ../www:/var/www
    ports:
      - "8081:80"
    links:
      - db
    environment:
      - DB_PORT=3306
      - DB_HOST=db
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_DATABASE=sistema
      - MYSQL_USER=sistema
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"